# Generated by Django 4.1.3 on 2023-12-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_category_slug_alter_course_category_and_more'),
        ('courses', '0008_alter_category_slug'),
    ]

    operations = [
    ]
